/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferConfirmationRouteImport } from './routes/transfer-confirmation'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as IndexRouteImport } from './routes/index'

const TransferConfirmationRoute = TransferConfirmationRouteImport.update({
  id: '/transfer-confirmation',
  path: '/transfer-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transfer': typeof TransferRoute
  '/transfer-confirmation': typeof TransferConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transfer': typeof TransferRoute
  '/transfer-confirmation': typeof TransferConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/transfer': typeof TransferRoute
  '/transfer-confirmation': typeof TransferConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/transfer' | '/transfer-confirmation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/transfer' | '/transfer-confirmation'
  id: '__root__' | '/' | '/transfer' | '/transfer-confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransferRoute: typeof TransferRoute
  TransferConfirmationRoute: typeof TransferConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer-confirmation': {
      id: '/transfer-confirmation'
      path: '/transfer-confirmation'
      fullPath: '/transfer-confirmation'
      preLoaderRoute: typeof TransferConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransferRoute: TransferRoute,
  TransferConfirmationRoute: TransferConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
