/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferConfirmationRouteImport } from './routes/transfer-confirmation'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TransferConfirmationRoute = TransferConfirmationRouteImport.update({
  id: '/transfer-confirmation',
  path: '/transfer-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deposit': typeof DepositRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/transfer-confirmation': typeof TransferConfirmationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deposit': typeof DepositRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/transfer-confirmation': typeof TransferConfirmationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deposit': typeof DepositRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/transfer-confirmation': typeof TransferConfirmationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/deposit'
    | '/signup'
    | '/transfer'
    | '/transfer-confirmation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/deposit'
    | '/signup'
    | '/transfer'
    | '/transfer-confirmation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/deposit'
    | '/signup'
    | '/transfer'
    | '/transfer-confirmation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DepositRoute: typeof DepositRoute
  SignupRoute: typeof SignupRoute
  TransferRoute: typeof TransferRoute
  TransferConfirmationRoute: typeof TransferConfirmationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer-confirmation': {
      id: '/transfer-confirmation'
      path: '/transfer-confirmation'
      fullPath: '/transfer-confirmation'
      preLoaderRoute: typeof TransferConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DepositRoute: DepositRoute,
  SignupRoute: SignupRoute,
  TransferRoute: TransferRoute,
  TransferConfirmationRoute: TransferConfirmationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
